services:
    update_project_info_service: '@App\Consumer\UpdateProjectInformation'
    librecores.util.githubapiservice: '@Librecores\ProjectRepoBundle\Service\GitHub\GitHubApiService'
    librecores.util.queuedispatcherservice: '@Librecores\ProjectRepoBundle\Service\QueueDispatcherService'
    librecores.util.markuptohtmlconverter:  '@App\Util\MarkupToHtmlConverter'
    app.form.type.project: '@App\Form\Type\ProjectType'
    app.form.type.organization: '@App\Form\Type\OrganizationType'
    librecores.form_extention.icon: '@App\Form\Extension\ButtonTypeIconExtension'
    librecores.form.type.purified_textarea: '@App\Form\Type\PurifiedTextareaType'
    librecores.form.transformer.html_purifier: '@Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer'
    validator.user_org_name: '@App\Validator\Constraints\UserOrgNameValidator'
    librecores_user_manager: '@App\Security\UserManager'
    librecores_user_provider: '@App\Security\Core\User\LibreCoresUserProvider'
    librecores.user.registration_event_listener: '@App\EventListener\OAuthRegistrationListener'
    librecores_project_voter: '@App\Security\ProjectVoter'
    librecores.process_creator: '@App\Util\ProcessCreator'
    librecores.repocrawlerfactory: '@App\RepoCrawler\RepoCrawlerFactory'
