# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: legacy_aliases.yml }


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Consumer Services (called through RabbitMQ)
    App\Consumer\UpdateProjectInformation: ~

    # Utilities
    Librecores\ProjectRepoBundle\Util\MarkupToHtmlConverter:
        arguments:
            - '@logger'
            - '@exercise_html_purifier.default'

    App\Service\GitHub\GitHubApiService:
        arguments:
            - '@app.cache.githubapi'
            - '@router'

    App\Service\QueueDispatcherService:
        calls:
            - [setContainer, ['@service_container']]

    App\RepoCrawler\RepoCrawlerFactory: ~
