imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc
#    cache:
#        app: cache.adapter.redis
#        default_redis_provider: "redis://localhost"

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# sentry
sentry:
    dsn: "%sentry_dsn%"
    options:
        environment: "%sentry_env%"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
