services:
    librecores.util.githubapiservice: '@App\Service\GitHub\GitHubApiService'
    librecores.util.queuedispatcherservice: '@App\Service\QueueDispatcherService'
    librecores.util.markuptohtmlconverter:  '@App\Util\MarkupToHtmlConverter'
    app.form.type.project: '@App\Form\Type\ProjectType'
    app.form.type.organization: '@App\Form\Type\OrganizationType'
    librecores.form_extention.icon: '@App\Form\Extension\ButtonTypeIconExtension'
    validator.user_org_name: '@App\Validator\Constraints\UserOrgNameValidator'
    librecores_user_manager: '@App\Security\UserManager'
    librecores_user_provider: '@App\Security\Core\User\LibreCoresUserProvider'
    librecores.user.registration_event_listener: '@App\EventListener\OAuthRegistrationListener'
    librecores_project_voter: '@App\Security\ProjectVoter'
    librecores.process_creator: '@App\Util\ProcessCreator'
