# HWIOAuthBundle
hwi_oauth_routing:
    resource: 'routes/hwi_oauth.yml'

fos_user_routing:
    resource: 'routes/fos_user.yml'

librecores_site:
    resource: "routes/site.yml"
    prefix:   /static

# Planet routes
librecores_planet:
    resource: "routes/planet.yml"
    prefix:   /planet

# Project Repository Routes
librecores_project_repo:
    resource: 'routes/project_repo.yml'


github_login:
    path: /user/connect/check-github

google_login:
    path: /user/connect/check-google

librecores.user.settings.oauth-disconnect:
    path: /user/disconnect/{serviceName}
    defaults: { _controller: LibrecoresProjectRepoBundle:User:disconnectFromOAuthService }

librecores.user.settings.profile:
    path: /user/settings/profile
    defaults: { _controller: LibrecoresProjectRepoBundle:User:profileSettings }

librecores.user.settings.connections:
    path: /user/settings/connected-services
    defaults: { _controller: LibrecoresProjectRepoBundle:User:connectionsSettings }

librecores.user.settings.password:
    path: /user/settings/password
    defaults: { _controller: LibrecoresProjectRepoBundle:User:passwordSettings }

librecores_user_resend_confirmation:
    path: /user/resend-confirmation
    defaults: { _controller: LibrecoresProjectRepoBundle:User:resendConfirmationEmail }
