assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        cssrewrite: ~
        jsqueeze: ~
    assets:
        # JavaScript files loaded inside <head> (only for special cases)
        js_head:
            inputs:
                - "assets/js/respond.min.js"
                - "assets/js/html5shiv.min.js"

        # JavaScript files loaded at the bottom of <body> (preferred)
        js_body_end:
            inputs:
                - "assets/js/jquery.min.js"
                - "assets/js/bootstrap.min.js"
                - "assets/js/moment.min.js"
                - "assets/js/livestamp.js"
