- name: Create destination directory for phpMyAdmin
  file:
    path: /var/www/phpmyadmin
    state: directory

- name: Download and extract phpMyAdmin
  unarchive:
    src: https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.tar.gz
    dest: /var/www/phpmyadmin
    remote_src: yes
    extra_opts:
      '--strip-components=1'

- name: Configure site for phpmyadmin
  file:
    path: /var/www/phpmyadmin/tmp
    state: directory
    owner: www-data

- name: Make phpmyadmin log directory
  file:
    path: /var/log/nginx/phpmyadmin
    state: directory

- name: Add nginx config for phpmyadmin
  template:
    src: ../templates/phpmyadmin.tpl
    dest: /etc/nginx/sites-available/phpmyadmin

- name: Enable phpmyadmin
  file:
    path: /etc/nginx/sites-enabled/phpmyadmin
    src: /etc/nginx/sites-available/phpmyadmin
    state: link
  notify: restart nginx
